# To find distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100
# Defining master set to hold all the unique elements
unique_elements = set()
# Computing power and placing in set
for a in range(2,101):
    for b in range(2,101):
        unique_elements.add(a**b)
# Returning length of set to get no. of elements
print(f"The number of distinct terms: {len(unique_elements)}")